version: '3.7'

services:
  server:
    build:
      context: ./yait-server
      dockerfile: Dockerfile
    image: yait-server
    container_name: yait-server
    command: npm start
    volumes:
      - ./yait-server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - yait-network
        
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - yait-network
    logging:
      driver: none

  client:
    build:
      context: ./yait-client
      dockerfile: Dockerfile
    image: yait-client
    container_name: yait-client
    command: npm start
    volumes:
      - ./yait-client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - yait-network
    environment:
      CHOKIDAR_USEPOLLING: "true"

networks:
    yait-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local